version: "3.9"
networks:
  pyciemss:
    driver: bridge
    name: pyciemss
  data-api:
    #TODO Remove in production
    external: true
services:
  api:
    container_name: pyciemss-api
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - api.env
    networks:
      - pyciemss
      - data-api # TODO Remove in production
    depends_on:
      - redis
      - pika
    volumes:
      - $PWD/api:/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - pyciemss
  rqworker:
    container_name: pyciemss-worker
    build:
      context: ./
      dockerfile: workers/Dockerfile
    env_file:
      - api.env
    depends_on:
      - redis
    networks:
      - pyciemss
      - data-api
  pika:
    container_name: pika_service
    hostname: my_rabit
    image: 'rabbitmq:3'
    ports:
      - "5672:5672"
    env_file:
      - api.env
    networks:
      - pyciemss