version: "3.9"
networks:
  pyciemss-api:
    driver: bridge
    name: pyciemss-api
  data-api:
    #TODO Remove in production
    external: true
services:
  api:
    container_name: pyciemss-api
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - api.env
    networks:
      - pyciemss-api
      - data-api # TODO Remove in production
    depends_on:
      - redis
    volumes:
      - $PWD/api:/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - pyciemss-api
  rqworker:
    build:
      context: ./
      dockerfile: operations/Dockerfile
    command:
      - rq
      - worker
      - --url
      - redis://redis.pyciemss-api:6379
      - high
      - default
      - low
    env_file:
      - api.env
    depends_on:
      - redis
    networks:
      - pyciemss-api
      - data-api
